general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 14

[window]
padding.x = 14
padding.y = 14
decorations = "None"
# opacity = 0.85
# dynamic_title = true
# startup_mode = "Windowed"
# title = "Terminal"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[cursor.style]
blinking = "On"

#[font]
#size = 13.0

#[font.bold]
#family = "Iosevka Nerd Font"
#style = "Bold"

#[font.italic]
#family = "Iosevka Nerd Font"
#style = "Italic"

#[font.normal]
#family = "Iosevka Nerd Font"
#style = "Regular"

[scrolling]
history = 50000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

# [window]
# decorations = "None"
# dynamic_title = true
# opacity = 0.85
# startup_mode = "Windowed"
# title = "Terminal"

#[window.padding]
#x = 10
#y = 10
